# Generated by Django 4.1.7 on 2023-05-08 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradation', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Градация зараженности',
                'verbose_name_plural': 'Градации зараженности',
            },
        ),
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
            },
        ),
        migrations.CreateModel(
            name='ResultScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_target', models.CharField(max_length=50)),
                ('cve_id', models.CharField(default='1', max_length=50)),
                ('protocol', models.CharField(default='1', max_length=10)),
                ('scan_data', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 21, 11, 553032))),
                ('gradation', models.CharField(default='1', max_length=50)),
            ],
            options={
                'verbose_name': 'Результат сканирования',
                'verbose_name_plural': 'Результаты сканирования',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 21, 11, 491061))),
                ('user_group', models.BooleanField(default='True')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CVES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CVE_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('CVSS', models.FloatField()),
                ('protocol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.protocols')),
            ],
            options={
                'verbose_name': 'Уязвимость',
                'verbose_name_plural': 'Уязвимости',
            },
        ),
    ]
