# Generated by Django 4.1.7 on 2023-05-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscan',
            name='scan_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 27, 55, 915744)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 27, 55, 852748)),
        ),
    ]
