# Generated by Django 4.1.7 on 2023-05-08 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_resultscan_scan_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='resultscan',
            name='scan_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 46, 5, 955019)),
        ),
    ]
