# Generated by Django 4.1.7 on 2023-05-08 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_users_alter_resultscan_scan_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscan',
            name='scan_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 19, 1, 11, 657789)),
        ),
    ]
